frequency: 1
nodes: [/gui_msg_concat_node, /ros/node_monitor, /ros/node_ressource_monitor, /ros/statistics_monitor, /ros/tf_monitoring, /ros/topic_monitor, /rosout, /system/cpu_frequency_monitor, /system/cpu_monitor, /system/network_monitor, /system/ntp_monitor, /system/ram_monitor, /system/wifi_monitor]

monitoring:
    frequency: 2
monitor_mode : 2
#AggregationStrategies mode: 1 LAST, 2 FIRST, 3 MIN, 4 MAX, 5 AVG#
