frequency: 1
nodes: [/cpu_monitor, /ram_monitor, /topic_monitor, /node_monitor, /network_monitor]

monitoring:
    frequency: 2
monitor_mode : 2
#AggregationStrategies mode: 1 LAST, 2 FIRST, 3 MIN, 4 MAX, 5 AVG#
