frequency: 1
nodes: [/system/cpu_monitor, /system/ram_monitor, /ros/topic_monitor, /ros/node_monitor, /system/network_monitor]

monitoring:
    frequency: 2
monitor_mode : 2
#AggregationStrategies mode: 1 LAST, 2 FIRST, 3 MIN, 4 MAX, 5 AVG#
