frequency: 2
# 0 = default(list all), 1 = whitelist, 2 = blacklist
filter_type: 2
node_list: ["monitor"] #exclude nodes that has "monitor" in the node-name

monitor_mode: 3
#AggregationStrategies mode: 1 LAST, 2 FIRST, 3 MIN, 4 MAX, 5 AVG#

