monitoring:
  frequency: 1
monitor_mode : 5
#AggregationStrategies mode: 1 LAST, 2 FIRST, 3 MIN, 4 MAX, 5 AVG#
timeTilDelete: 3
topics: [test]

test:
  topic: /monitoring
  source: /monitor_gui
  destination: /statistics_monitoring
  frequency: 1
  size: 321
  dFrequency: 1
  dSize: 100
  type: geometry_msgs::Twist
  errorlevel: 0.5
