monitoring:
  frequency: 1
timeTilDelete: 3
topics: [monitoring]

monitoring:
  topic: /monitoring/gui
  source: /gui_msg_concat_node
  destination: /statistics_monitoring
  frequency: 1
  dFrequency: 0.5
  size: 0
  dSize: 1
  type: geometry_msgs::Twist
  errorlevel: 0.5
