monitoring:
  frequency: 1
timeTilDelete: 3
topics: [turtlesim]

turtlesim:
  topic: /monitoring
  source: /monitor_gui
  destination: /statistics_monitoring
  frequency: 2
  size: 0
  dFrequency: 1
  dSize: 1
  type: geometry_msgs::Twist
  errorlevel: 0.5
