avarage: true   #the Average of the Last Minute. New info every 5s (Calculated by Kernel)
percent: true   #The Average over frequency/1s in percent
percentPerCore: true  #like percent but for every core
processes: false    #parsed output of ps aux
temperature: true   #temperature of the CPU

frequency: 2    #Publish and calculation frequency


